highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://www.stevenwade.co.uk/resume
author: Steven Wade

# edit this section with your information
# www.stevenwade.co.uk - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Steven Wade's Resume
name: Steven Wade
email: steven@stevenwade.co.uk
email_full: mailto:steven@stevenwade.co.uk
website: www.stevenwade.co.uk
website_full: http://www.stevenwade.co.uk
github: swade1987
twitter: swade1987
tel: +44 07738 221 296
tel_full: tel:+4407738221296
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
postcode:
city: Kent
country: United Kingdom
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
